import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  LucideAngularModule,
  File,
  House,
  Menu,
  UserCheck,
  MessageCircle,
  MessageSquarePlus,
  Search,
  Phone,
  Settings,
  Mail,
  User,
  Lock,
  Eye,
  EyeClosed,
  LogOut,
  EllipsisVertical,
  Video,
  Image,
  Paperclip,
  Smile,
  Send,
  X,
  Check,
  Clock,
  Globe,
  Edit,
  UserX,
  PhoneIncoming,
  PhoneMissed,
} from 'lucide-angular';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    LucideAngularModule.pick({
      File,
      House,
      Mail,
      Lock,
      Menu,
      User,
      UserCheck,
      Eye,
      EyeClosed,
      MessageCircle,
      MessageSquarePlus,
      Search,
      Phone,
      Settings,
      LogOut,
      EllipsisVertical,
      Video,
      Image,
      Paperclip,
      Smile,
      Send,
      X,
      Check,
      Clock,
      Globe,
      Edit,
      UserX,
      PhoneMissed,
      PhoneIncoming
    }),
  ],
  exports: [CommonModule, FormsModule, ReactiveFormsModule, LucideAngularModule],
})
export class SharedModule {}
